FROM {{ from }}
MAINTAINER {{ maintainer | safe }}

RUN yum install -y make gcc-c++

# Retrieve GPG keys
RUN gpg --keyserver pool.sks-keyservers.net --recv-keys \
	9554F04D7259F04124DE6B476D5A82AC7E37093B \
	94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
	0034A06D9D9B0064CE8ADF6BF1747F4AD2306D93 \
	FD3A5288F042B6850C66B31F09FE44734EB7990E \
	71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
	DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
	C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
	B9AE9905FFD7803F25714661B63B535A4C206CA9

# Create temp directory
RUN mkdir -p /tmp/node/{{ source.dir }} \
&& pushd /tmp/node/{{ source.dir }} \

# Download and verify Node source code
&& curl -Lo {{ checksum.file }} {{ checksum.url }} \
&& curl -Lo {{ signature.file }}  {{ signature.url }} \
&& curl -Lo {{ source.file }} {{ source.url }} \
&& gpg --verify {{ signature.file }} \
&& grep {{ source.file }} {{ checksum.file }} | sha256sum -c - \
&& echo "{{ source.hash }}  {{ source.file }}" | sha256sum -c - \

# Extract and compile source
&& mkdir -p /opt/node/{{ source.dir }} \
&& tar -xzf {{ source.file }} -C /tmp/node \
&& pushd /tmp/node/{{ source.dir }} \
&& ./configure --prefix /opt/node/{{ source.dir }} \
&& make \
&& make install \
&& popd \
&& popd \
&& rm -rf /tmp/node

# Set Path environment variable
ENV PATH $PATH:/opt/node/{{ source.dir }}/bin

RUN npm install -g npm
