FROM {{ from }}
MAINTAINER {{ maintainer | safe }}

RUN yum install -y unzip

# Create temp directory
RUN mkdir -p /tmp/java/{{ binaries.dir }} \
&& pushd /tmp/java/{{ binaries.dir }} \

# Download and verify JDK RPM and Java Cryptography Extension zip
&& curl -Lj -o {{ binaries.file }} -H "Cookie: oraclelicense=accept-securebackup-cookie" {{ binaries.url }} \
&& curl -Lj -o {{ jce.binaries.file }} -H "Cookie: oraclelicense=accept-securebackup-cookie" {{ jce.binaries.url }} \
&& echo "{{ binaries.hash }}  {{ binaries.file }}" | sha256sum -c - \
&& echo "{{ jce.binaries.hash }}  {{ jce.binaries.file }}" | sha256sum -c - \

# Install JDK RPM and JCE
&& mkdir -p /opt/java \
&& chmod +x {{ binaries.file }} \
&& ./{{ binaries.file }} \
&& ls -al \
&& mv /tmp/java/{{ binaries.dir }}/{{ binaries.dir }} /opt/java/{{ binaries.dir }} \
&& unzip {{ jce.binaries.file }} -d /tmp/java/{{ binaries.dir }} \
&& mv /tmp/java/{{ binaries.dir }}/{{ jce.binaries.dir }}/*.jar /opt/java/{{ binaries.dir }}/jre/lib/security \
&& popd \
&& rm -rf /tmp/java

ENV JAVA_HOME /opt/java/{{ binaries.dir }}
ENV PATH $PATH:$JAVA_HOME/bin:$JAVA_HOME/jre/bin

